# azure-pipelines.yml

pool:
  vmImage: 'ubuntu-18.04'

parameters:
- name: option
  displayName: Option
  type: string
  default: stressOptions
  values:
  - stressOptions
  - smokeOptions

steps:
  - script: |
      ls
      docker pull loadimpact/k6
    displayName: Pull k6 image
  - script: |
      docker run -i \
        -v `pwd`:/src \
        loadimpact/k6 \
        run -e options=${{ parameters.option }} /src/012_azure_pipelines/http_get.js \
    displayName: Run k6 cloud